# Generated by Django 5.0.6 on 2025-08-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Myaba Media Tech', max_length=200)),
                ('tagline', models.CharField(default='Professional ICT, Media & Publishing Solutions', max_length=300)),
                ('description', models.TextField(default='Leading ICT and media company serving the Nkangala District Municipality')),
                ('phone', models.CharField(default='+27 81 410 9337', max_length=20)),
                ('email', models.EmailField(default='info@myabamediatech.com', max_length=254)),
                ('address', models.TextField(default='29 Geldenhuys, Delmas')),
                ('website', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('whatsapp', models.CharField(default='27814109337', max_length=20)),
                ('founded_year', models.PositiveIntegerField(default=2012)),
                ('employees_count', models.PositiveIntegerField(default=15)),
                ('projects_completed', models.PositiveIntegerField(default=500)),
                ('happy_clients', models.PositiveIntegerField(default=150)),
                ('years_experience', models.PositiveIntegerField(default=8)),
                ('meta_description', models.TextField(blank=True, max_length=160)),
                ('meta_keywords', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profile',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General'), ('services', 'Services'), ('pricing', 'Pricing'), ('technical', 'Technical'), ('support', 'Support')], default='general', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('web', 'Web Development'), ('design', 'Graphic Design'), ('news', 'News & Media'), ('system', 'System Development'), ('marketing', 'Digital Marketing')], max_length=20)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('development', 'In Development'), ('testing', 'Testing'), ('completed', 'Completed'), ('maintenance', 'Maintenance')], default='completed', max_length=20)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('gallery_images', models.TextField(blank=True, help_text='Comma-separated image URLs')),
                ('client_name', models.CharField(blank=True, max_length=100)),
                ('project_url', models.URLField(blank=True)),
                ('technologies', models.TextField(blank=True, help_text='Comma-separated technologies')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-is_featured', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('ceo', 'Chief Executive Officer'), ('cto', 'Chief Technology Officer'), ('developer', 'Web Developer'), ('designer', 'Graphic Designer'), ('journalist', 'Journalist'), ('manager', 'Project Manager'), ('marketing', 'Marketing Specialist'), ('support', 'Customer Support')], max_length=20)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated skills')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('joined_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name'],
            },
        ),
    ]
